import Head from 'next/head'
import About from '../components/about'
import Contact from '../components/contact'
import Main from '../components/main'
import Projects from '../components/projects'
import Certifications from '../components/certifications'



export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Anand Pandey || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    <About />
    <Projects />
    <Certifications />
    <Contact />
      
    </div>
  )
}
