import Head from "next/head";
import FrontPage from "../Components/FrontPage";
import Projects from "../Components/Projects";
import Skills from "../Components/Skills";
import Contact from "../Components/Contact";

// import Navbar from "../Components/navbar"




export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Anand Pandey || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrontPage/>
      <Projects/>
      <Skills/>
      <Contact/>

     
      
    </div>
  );
}
